/// Predefined vocabulary by topic (English ↔ Uzbek).
class VocabTopic {
  final String id;
  final String emoji;
  final String title;
  final List<(String, String)> words; // (english, uzbek)
  const VocabTopic({
    required this.id,
    required this.emoji,
    required this.title,
    required this.words,
  });
}

const vocabTopics = <VocabTopic>[
  VocabTopic(
    id: 'restaurant',
    emoji: '🍽️',
    title: 'Restoranda',
    words: [
      ('menu', 'menyu'),
      ('waiter', 'ofitsiant'),
      ('order', 'buyurtma'),
      ('bill', 'hisob'),
      ('appetizer', 'gazak'),
      ('main course', 'asosiy taom'),
      ('dessert', 'shirinlik'),
      ('reservation', 'oldindan band qilish'),
      ('tip', 'choychaqa'),
      ('vegetarian', 'vegetarian'),
      ('spicy', 'achchiq'),
      ('delicious', 'mazali'),
      ('breakfast', 'nonushta'),
      ('lunch', 'tushlik'),
      ('dinner', 'kechki ovqat'),
    ],
  ),
  VocabTopic(
    id: 'travel',
    emoji: '✈️',
    title: 'Sayohat',
    words: [
      ('airport', 'aeroport'),
      ('flight', 'reys'),
      ('passport', 'pasport'),
      ('luggage', 'yuk'),
      ('boarding pass', 'chiqish kartasi'),
      ('gate', 'darvoza'),
      ('check-in', 'ro\'yxatdan o\'tish'),
      ('departure', 'jo\'nash'),
      ('arrival', 'yetib kelish'),
      ('customs', 'bojxona'),
      ('hotel', 'mehmonxona'),
      ('reservation', 'band qilish'),
      ('suitcase', 'jamadon'),
      ('tour', 'sayohat'),
      ('souvenir', 'esdalik'),
    ],
  ),
  VocabTopic(
    id: 'work',
    emoji: '💼',
    title: 'Ish va karyera',
    words: [
      ('interview', 'suhbat'),
      ('resume', 'rezyume'),
      ('employer', 'ish beruvchi'),
      ('employee', 'xodim'),
      ('salary', 'maosh'),
      ('promotion', 'lavozimga ko\'tarilish'),
      ('deadline', 'muddat'),
      ('meeting', 'yig\'ilish'),
      ('colleague', 'hamkasb'),
      ('boss', 'rahbar'),
      ('overtime', 'qo\'shimcha ish'),
      ('teamwork', 'jamoa ishi'),
      ('skill', 'mahorat'),
      ('experience', 'tajriba'),
      ('feedback', 'fikr-mulohaza'),
    ],
  ),
  VocabTopic(
    id: 'health',
    emoji: '🩺',
    title: 'Sog\'liq',
    words: [
      ('doctor', 'shifokor'),
      ('nurse', 'hamshira'),
      ('hospital', 'kasalxona'),
      ('pharmacy', 'dorixona'),
      ('prescription', 'retsept'),
      ('headache', 'bosh og\'rig\'i'),
      ('fever', 'isitma'),
      ('cough', 'yo\'tal'),
      ('allergy', 'allergiya'),
      ('injury', 'jarohat'),
      ('treatment', 'davolash'),
      ('appointment', 'qabul'),
      ('symptom', 'alomat'),
      ('healthy', 'sog\'lom'),
      ('sick', 'kasal'),
    ],
  ),
  VocabTopic(
    id: 'shopping',
    emoji: '🛒',
    title: 'Xarid',
    words: [
      ('price', 'narx'),
      ('discount', 'chegirma'),
      ('receipt', 'chek'),
      ('cashier', 'kassir'),
      ('size', 'o\'lcham'),
      ('fitting room', 'kiyim sinash xonasi'),
      ('refund', 'pul qaytarish'),
      ('exchange', 'almashtirish'),
      ('brand', 'brend'),
      ('quality', 'sifat'),
      ('cheap', 'arzon'),
      ('expensive', 'qimmat'),
      ('sale', 'aksiya'),
      ('shopping cart', 'savatcha'),
      ('credit card', 'plastik karta'),
    ],
  ),
  VocabTopic(
    id: 'tech',
    emoji: '💻',
    title: 'Texnologiya',
    words: [
      ('computer', 'kompyuter'),
      ('laptop', 'noutbuk'),
      ('software', 'dasturiy ta\'minot'),
      ('hardware', 'apparat'),
      ('internet', 'internet'),
      ('website', 'veb-sayt'),
      ('email', 'elektron pochta'),
      ('password', 'parol'),
      ('download', 'yuklab olish'),
      ('upload', 'yuklash'),
      ('update', 'yangilash'),
      ('cloud', 'bulut'),
      ('app', 'ilova'),
      ('screen', 'ekran'),
      ('battery', 'batareya'),
    ],
  ),
  VocabTopic(
    id: 'family',
    emoji: '👨‍👩‍👧',
    title: 'Oila',
    words: [
      ('parent', 'ota-ona'),
      ('father', 'ota'),
      ('mother', 'ona'),
      ('brother', 'aka/uka'),
      ('sister', 'opa/singil'),
      ('grandfather', 'bobo'),
      ('grandmother', 'buvi'),
      ('uncle', 'amaki'),
      ('aunt', 'amma/xola'),
      ('cousin', 'amakivachcha'),
      ('nephew', 'jiyan (o\'g\'il)'),
      ('niece', 'jiyan (qiz)'),
      ('husband', 'er'),
      ('wife', 'xotin'),
      ('relatives', 'qarindoshlar'),
    ],
  ),
  VocabTopic(
    id: 'emotions',
    emoji: '😊',
    title: 'Hissiyotlar',
    words: [
      ('happy', 'baxtli'),
      ('sad', 'xafa'),
      ('angry', 'jahldor'),
      ('scared', 'qo\'rqqan'),
      ('surprised', 'ajablangan'),
      ('tired', 'charchagan'),
      ('excited', 'hayajonli'),
      ('bored', 'zerikkan'),
      ('proud', 'mag\'rur'),
      ('worried', 'tashvishli'),
      ('lonely', 'yolg\'iz'),
      ('confident', 'ishonchli'),
      ('nervous', 'xavotirda'),
      ('calm', 'tinch'),
      ('curious', 'qiziquvchan'),
    ],
  ),
];
