import 'package:flutter/material.dart';
import '../../core/theme.dart';

/// Roleplay Scenario v2: rich character-driven mini-conversations.
/// Each scenario carries an AI persona [role], a learner [goal], and
/// vocabulary hints surfaced as quick-tap chips before the chat starts.
class Scenario {
  final String emoji;
  final String title;
  final String description;
  final String subject;
  final String openingUserMessage;
  final Color color;
  // v2:
  final String role; // AI character — e.g. "friendly Italian barista in Rome"
  final String goal; // Learner's objective in this scene
  final List<String> phrases; // Useful phrase hints (3-5)
  final String difficulty; // 'A1' | 'A2' | 'B1' | 'B2'

  const Scenario({
    required this.emoji,
    required this.title,
    required this.description,
    required this.subject,
    required this.openingUserMessage,
    required this.color,
    this.role = '',
    this.goal = '',
    this.phrases = const [],
    this.difficulty = 'A2',
  });
}

const scenarios = <Scenario>[
  // ─── ENGLISH — Daily life ───
  Scenario(
    emoji: '☕',
    title: 'Kafeda buyurtma',
    description: 'Kofe yoki choy buyurtma berishni mashq qiling',
    subject: 'english',
    openingUserMessage: "Hi! I'd like to order a coffee. What do you recommend?",
    color: AppColors.fire,
    role: 'a friendly barista in a busy Brooklyn cafe',
    goal: 'order a drink, a small snack, and pay',
    phrases: ['I\'ll have...', 'How much is it?', 'For here please', 'Cash or card?'],
    difficulty: 'A1',
  ),
  Scenario(
    emoji: '✈️',
    title: 'Aeroportda',
    description: 'Reys haqida savol berish va check-in',
    subject: 'english',
    openingUserMessage: "Excuse me, I have a question about my flight to London.",
    color: AppColors.secondary,
    role: 'an airline check-in agent at JFK airport',
    goal: 'check in for a flight, deal with a delayed bag',
    phrases: ['Window or aisle?', 'Boarding pass', 'Gate number', 'What time does it board?'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🏨',
    title: 'Mehmonxonada',
    description: 'Xona band qilish va savollar',
    subject: 'english',
    openingUserMessage: "Hello! I'd like to check in. I have a reservation under my name.",
    color: AppColors.gold,
    role: 'a hotel receptionist at a 4-star hotel',
    goal: 'check in, ask about Wi-Fi, breakfast hours, and book a wake-up call',
    phrases: ['Single room', 'Wi-Fi password', 'Breakfast included?', 'Wake-up call at 7'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🛒',
    title: 'Do\'konda',
    description: 'Kiyim sotib olish, narx so\'rash',
    subject: 'english',
    openingUserMessage: "Hi, I'm looking for a blue shirt. Do you have one in size M?",
    color: AppColors.heart,
    role: 'a helpful sales assistant in a clothing store',
    goal: 'find a shirt in the right size, try it on, and buy it',
    phrases: ['Fitting room', 'Do you have it in...', 'On sale', 'I\'ll take it'],
    difficulty: 'A1',
  ),
  Scenario(
    emoji: '🩺',
    title: 'Shifokorda',
    description: 'Soglik ahvolini tushuntirish',
    subject: 'english',
    openingUserMessage: "Hello doctor, I haven't been feeling well for a few days.",
    color: AppColors.primary,
    role: 'an English-speaking doctor at a clinic',
    goal: 'describe symptoms, ask for medicine, and understand the diagnosis',
    phrases: ['I have a headache', 'For three days', 'Any side effects?', 'Take with food'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '💼',
    title: 'Ish suhbati',
    description: 'O\'zingiz haqingizda gapirish',
    subject: 'english',
    openingUserMessage: "Thank you for inviting me. I'd like to tell you about my background.",
    color: AppColors.secondary,
    role: 'a senior hiring manager at a tech company conducting a phone screen',
    goal: 'introduce yourself, talk about experience, and answer "why this company"',
    phrases: ['My background is in...', 'I\'m passionate about', 'A challenge I faced', 'I\'d love to learn more about'],
    difficulty: 'B2',
  ),
  Scenario(
    emoji: '🚕',
    title: 'Taksida',
    description: 'Manzilni aytish va narx',
    subject: 'english',
    openingUserMessage: "Hi, can you take me to the train station, please? How much will it cost?",
    color: AppColors.fire,
    role: 'a NYC taxi driver with a strong personality',
    goal: 'agree on price, get to a destination, and pay',
    phrases: ['How long will it take?', 'Keep the change', 'Could you slow down?', 'Drop me off here'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🎓',
    title: 'Universitetda',
    description: 'Imtihon haqida savol',
    subject: 'english',
    openingUserMessage: "Excuse me, I have a question about the exam schedule.",
    color: AppColors.primary,
    role: 'a university administrative officer',
    goal: 'find out the exam date, deadline, and how to register',
    phrases: ['Could you clarify...', 'The deadline for...', 'I\'m enrolled in...', 'Where is the exam held?'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '🤝',
    title: 'Yangi tanishuv',
    description: 'O\'zingizni tanishtirish',
    subject: 'english',
    openingUserMessage: "Hi! I'm new here. My name is Sam. What about you?",
    color: AppColors.gold,
    role: 'a friendly American expat at a language meetup',
    goal: 'introduce yourself, ask about their interests, exchange contact info',
    phrases: ['Nice to meet you', 'Where are you from?', 'What do you do?', 'Let\'s keep in touch'],
    difficulty: 'A1',
  ),
  Scenario(
    emoji: '📞',
    title: 'Telefon suhbati',
    description: 'Rasmiy qo\'ng\'iroq',
    subject: 'english',
    openingUserMessage: "Hello, I'm calling to make an appointment. Are you available this week?",
    color: AppColors.heart,
    role: 'a receptionist at a busy dental clinic',
    goal: 'book an appointment, ask about availability, confirm the time',
    phrases: ['Could I book...', 'Is Wednesday available?', 'Let me check', 'See you then'],
    difficulty: 'A2',
  ),

  // ─── ENGLISH — Travel & emergencies ───
  Scenario(
    emoji: '🗺️',
    title: 'Adashganda',
    description: 'Yo\'l so\'rash va xarita',
    subject: 'english',
    openingUserMessage: "Excuse me, could you tell me how to get to the museum?",
    color: AppColors.secondary,
    role: 'a friendly local on the street in London',
    goal: 'ask directions, understand turns and landmarks, thank politely',
    phrases: ['Turn left at...', 'Go straight', 'About 10 minutes', 'Thanks a lot'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🍽️',
    title: 'Restoranda',
    description: 'Menyu o\'qish, ovqat buyurtma berish',
    subject: 'english',
    openingUserMessage: "Hi! Could we see the menu, please? And do you have any vegetarian options?",
    color: AppColors.fire,
    role: 'a waiter at an Italian restaurant',
    goal: 'order starter + main + drink, ask for the bill, leave a tip',
    phrases: ['I\'ll have the...', 'Could I get...', 'Could we have the bill?', 'Is service included?'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🆘',
    title: 'Favqulodda holat',
    description: 'Politsiya yoki yordam chaqirish',
    subject: 'english',
    openingUserMessage: "Help! I\'ve lost my wallet. What should I do?",
    color: AppColors.heart,
    role: 'a calm police officer at a station',
    goal: 'report a lost item, give your details, get a reference number',
    phrases: ['I\'d like to report...', 'It happened on...', 'My passport number is...', 'Could I have a copy?'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '🏦',
    title: 'Bankda',
    description: 'Hisob ochish, valyuta almashtirish',
    subject: 'english',
    openingUserMessage: "Hello, I\'d like to exchange some money and ask about opening an account.",
    color: AppColors.primary,
    role: 'a bank teller at a high-street branch',
    goal: 'exchange currency, ask about fees, open a basic account',
    phrases: ['What\'s the rate?', 'Any commission?', 'How long will it take?', 'I need to sign here?'],
    difficulty: 'B1',
  ),

  // ─── ENGLISH — Career / academic ───
  Scenario(
    emoji: '🎤',
    title: 'Konferensiyada',
    description: 'Tanishtiruv va savol berish',
    subject: 'english',
    openingUserMessage: "Hi, thanks for your talk. I had a question about your last slide.",
    color: AppColors.secondary,
    role: 'a confident keynote speaker after a tech talk',
    goal: 'ask a smart question, introduce yourself, exchange LinkedIn',
    phrases: ['That was insightful', 'My question is about...', 'Could you elaborate on...', 'Could we connect on LinkedIn?'],
    difficulty: 'B2',
  ),
  Scenario(
    emoji: '🧑‍💼',
    title: 'Boshliq bilan',
    description: 'Maoshni muhokama qilish',
    subject: 'english',
    openingUserMessage: "Could we talk for a few minutes? I\'d like to discuss my role.",
    color: AppColors.gold,
    role: 'your direct manager — supportive but tight on budget',
    goal: 'request a raise, justify it with achievements, agree on next steps',
    phrases: ['Based on my impact...', 'Market rate for', 'A bump of', 'I\'d appreciate your support'],
    difficulty: 'B2',
  ),
  Scenario(
    emoji: '📧',
    title: 'Mijoz bilan',
    description: 'Muammo hal qilish',
    subject: 'english',
    openingUserMessage: "Hi, thanks for reaching out. I see there\'s an issue with your order.",
    color: AppColors.heart,
    role: 'a polite but firm customer demanding a refund',
    goal: 'apologize, understand the issue, offer a fair solution',
    phrases: ['I\'m sorry to hear', 'Let me look into it', 'A partial refund of...', 'We\'ll fix this'],
    difficulty: 'B1',
  ),

  // ─── ENGLISH — Social / friendly ───
  Scenario(
    emoji: '🎂',
    title: 'Tug\'ilgan kunda',
    description: 'Tabriklash va sovg\'a',
    subject: 'english',
    openingUserMessage: "Happy birthday! How does it feel to be one year older?",
    color: AppColors.gold,
    role: 'a friend at their birthday party',
    goal: 'congratulate, give a compliment, suggest a toast',
    phrases: ['Happy birthday', 'You haven\'t aged a bit', 'Here\'s to', 'Let\'s raise a glass'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🎬',
    title: 'Kino haqida',
    description: 'Film tahlili',
    subject: 'english',
    openingUserMessage: "I just saw that new movie. What did you think of it?",
    color: AppColors.primary,
    role: 'a film-buff friend who loves debating cinema',
    goal: 'share opinion, agree/disagree politely, recommend another film',
    phrases: ['I thought it was', 'The acting was', 'It reminded me of', 'You should check out'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '🏋️',
    title: 'Sport zalda',
    description: 'Sportchi bilan suhbat',
    subject: 'english',
    openingUserMessage: "Hey, would you mind spotting me on this set?",
    color: AppColors.fire,
    role: 'a regular at the gym, willing to help newcomers',
    goal: 'ask for help with a workout, exchange tips, plan to train together',
    phrases: ['How many reps?', 'Could you spot me?', 'I\'m working on', 'See you tomorrow'],
    difficulty: 'A2',
  ),

  // ─── ENGLISH — IELTS / formal ───
  Scenario(
    emoji: '📝',
    title: 'IELTS Part 1',
    description: 'O\'zi haqida 12 savol',
    subject: 'english',
    openingUserMessage: "Good morning. Could you tell me your full name, please?",
    color: AppColors.gold,
    role: 'an official IELTS Speaking examiner — formal but kind',
    goal: 'answer Part 1 questions about hometown, work/study, and free time',
    phrases: ['Well, I\'d say', 'To be honest', 'In my experience', 'It depends on'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '🎤',
    title: 'IELTS Part 2 cue card',
    description: '2 min monolog',
    subject: 'english',
    openingUserMessage: "I\'d like you to describe a person who has influenced you. You have one minute to prepare.",
    color: AppColors.gold,
    role: 'an IELTS Speaking examiner running the long-turn task',
    goal: 'deliver a 2-minute coherent monologue with examples',
    phrases: ['Let me tell you about', 'What I admire most is', 'For instance', 'In conclusion'],
    difficulty: 'B2',
  ),

  // ─── RUSSIAN ───
  Scenario(
    emoji: '☕',
    title: 'Кофе заказать',
    description: 'Kafeda buyurtma — rus tilida',
    subject: 'russian',
    openingUserMessage: "Здравствуйте! Я хотел бы заказать кофе.",
    color: AppColors.heart,
    role: 'бариста в московской кофейне',
    goal: 'заказать напиток, узнать цену, оплатить',
    phrases: ['Можно мне...', 'Сколько стоит?', 'С собой', 'Спасибо большое'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🚇',
    title: 'В метро',
    description: 'Yo\'l so\'rash',
    subject: 'russian',
    openingUserMessage: "Извините, как доехать до Красной площади?",
    color: AppColors.heart,
    role: 'добрый москвич на станции метро',
    goal: 'спросить направление, понять номер линии',
    phrases: ['На какой станции?', 'Сколько остановок?', 'Прямо или с пересадкой?', 'Большое спасибо'],
    difficulty: 'B1',
  ),
  Scenario(
    emoji: '📞',
    title: 'Запись к врачу',
    description: 'Telefon orqali',
    subject: 'russian',
    openingUserMessage: "Здравствуйте, я хотел бы записаться на приём.",
    color: AppColors.heart,
    role: 'регистратор поликлиники',
    goal: 'записаться на приём, выбрать удобное время',
    phrases: ['В какое время?', 'Какой врач?', 'Запишите на', 'Подойдёт'],
    difficulty: 'B1',
  ),

  // ─── GERMAN ───
  Scenario(
    emoji: '🥨',
    title: 'In der Bäckerei',
    description: 'Bakeryda nemis tilida',
    subject: 'german',
    openingUserMessage: "Guten Morgen! Ich hätte gern zwei Brötchen, bitte.",
    color: AppColors.gold,
    role: 'eine freundliche Bäckereiverkäuferin in München',
    goal: 'Brot bestellen, Preis erfragen, bezahlen',
    phrases: ['Ich hätte gern...', 'Was kostet das?', 'Zum Mitnehmen', 'Stimmt so'],
    difficulty: 'A1',
  ),
  Scenario(
    emoji: '🎫',
    title: 'Am Bahnhof',
    description: 'Poyezd uchun chipta',
    subject: 'german',
    openingUserMessage: "Entschuldigung, eine Fahrkarte nach Berlin, bitte.",
    color: AppColors.gold,
    role: 'ein Schalterbeamter am Hauptbahnhof',
    goal: 'eine Fahrkarte kaufen, Verbindung und Preis erfragen',
    phrases: ['Hin und zurück', 'Einfache Fahrt', 'Wann fährt der nächste?', 'Welches Gleis?'],
    difficulty: 'A2',
  ),

  // ─── TURKISH ───
  Scenario(
    emoji: '🛍️',
    title: 'Çarşıda pazarlık',
    description: 'Bozorda narxlashish',
    subject: 'turkish',
    openingUserMessage: "Merhaba! Bu kaç para? Biraz indirim yapar mısınız?",
    color: AppColors.primary,
    role: 'İstanbul\'daki Kapalı Çarşı\'da deneyimli bir esnaf',
    goal: 'fiyat sormak, pazarlık etmek, almak',
    phrases: ['Çok pahalı', 'Biraz indirim?', 'Son fiyatınız?', 'Anlaştık'],
    difficulty: 'A2',
  ),
  Scenario(
    emoji: '🚖',
    title: 'Taksi çağırmak',
    description: 'Manzilni aytish',
    subject: 'turkish',
    openingUserMessage: "Merhaba, Sultanahmet\'e gidebilir misiniz?",
    color: AppColors.primary,
    role: 'sohbetçi bir İstanbul taksi şoförü',
    goal: 'taksiye binmek, fiyatı sormak, varış noktasına gitmek',
    phrases: ['Ne kadar tutar?', 'Trafik var mı?', 'Burada inebilir miyim?', 'Üstü kalsın'],
    difficulty: 'A2',
  ),

  // ─── MATH ───
  Scenario(
    emoji: '📐',
    title: 'Test masala',
    description: 'AI muammoni bosqichma-bosqich hal qiladi',
    subject: 'math',
    openingUserMessage: "Solve and explain step-by-step: 2x + 5 = 17.",
    color: AppColors.fire,
    role: 'a patient math tutor who explains every step',
    goal: 'solve a linear equation and check the answer',
    phrases: ['Step 1', 'Subtract', 'Divide both sides', 'Check the answer'],
    difficulty: 'A2',
  ),
];
